spring.application.name=UserRegistration

server.port=1111
spring.datasource.url=jdbc:postgresql://localhost:5432/Dronezzfly
spring.datasource.username=postgres
spring.datasource.password=Dronezz@1234
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
company.name=Dronezzfly