spring.application.name=CustomProperties_Value_ConfigurationProperties

# Custom Properties
app.name=springapplication
app.version=3.3.3
app.description=custom properties configuration

server.port=4444
#Custom Properties
student.id=101
student.name=ramesh
student.age=25
student.course=java

#Custom Properties
employee.id=49
employee.name=subramanya
employee.dept=developer
employee.salary=40000